### ISSUE TITLE
Creating commands in a type

### ISSUE THREAD

**Issue by dploeger** [akamensky/argparse#117]
I'm pretty sure this is just my lack of proper Go knowledge, but I'd like to create subcommands in a type and use the parameters in functions of that type.

For example:

```go
package main

import (
	"fmt"
	"github.com/akamensky/argparse"
	"os"
)

type Test struct {
	test *string
}

func (t Test) addCommand(parser *argparse.Parser) *argparse.Command {
	command := parser.NewCommand("test", "something to test")
	t.test = command.String("t", "test", &argparse.Options{
		Required: true,
	})
	return command
}

func (t Test) run() {
	print(*t.test)
}

func main() {
	parser := argparse.NewParser("test", "test")
	tester := Test{}
	command := tester.addCommand(parser)

	if err := parser.Parse(os.Args); err != nil {
		fmt.Print(parser.Usage(err))
		os.Exit(1)
	}

	if command.Happened() {
		tester.run()
	}
}
```

The output of this program is:

```bash
$ ./test test -t "test"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10296809c]

goroutine 1 [running]:
main.Test.run(...)
        /Users/dennis.ploeger/work/test/test.go:22
main.main()
        /Users/dennis.ploeger/work/test/test.go:36 +0xdc
```

So apparently, the parameter value was not stored in the type.

What am I doing wrong? I guess something with pointers?

Thanks!

**Comment by dploeger** [comment]
Of course, it *was* my missing Go knowledge. 😆 

In `addCommand`, the receiver needs to be a pointer receiver, so `NewCommand` can actually modify the test property:

```golang
func (t *Test) addCommand(parser *argparse.Parser) *argparse.Command {
```
