### ISSUE TITLE
Can't have duplicate switches in different commands?

### ISSUE THREAD

**Issue by lespea** [akamensky/argparse#79]
If different commands both have switches that share the same short or long value, it errors with `unable to add String: short name {} occurs more than once`.  This completely renders this library unusable for me unfortunately as many of my sub-commands do share the same switches (with different uses).  Is this something that would be easy to fix or should I look for another library?

**Comment by akamensky** [comment]
@lespea can you please provide minimal code that shows this bug? If the subcommands that use same short-name and long-name are on different branches of the command tree, there should be no such error and then it would be a bug.

**Comment by akamensky** [comment]
@lespea I have just tested and I don't see this issue at all:

```
package main

import (
	"fmt"
	"github.com/akamensky/argparse"
	"os"
)

func main() {
	p := argparse.NewParser("test", "test")

	c1 := p.NewCommand("c1", "c1")
	c2 := p.NewCommand("c2", "c2")

	arg1 := c1.String("s", "str", &argparse.Options{
		Help:    "arg1 in c1",
		Default: "arg1",
	})
	arg2 := c2.String("s", "str", &argparse.Options{
		Help:    "arg2 in c2",
		Default: "arg2",
	})

	err := p.Parse(os.Args)
	if err != nil {
		panic(err)
	}

	if c1.Happened() {
		fmt.Println(*arg1)
	} else if c2.Happened() {
		fmt.Println(*arg2)
	} else {
		fmt.Println("pick either c1 or c2")
	}
}
```

The result of running:

```
(base) [alexey.kamenskiy@macbook-pro:test]$ go run main.go c1
arg1
(base) [alexey.kamenskiy@macbook-pro:test]$ go run main.go c2
arg2
(base) [alexey.kamenskiy@macbook-pro:test]$
```

I imagine that you trying to add the same argument short-name or long-name within the SAME branch of subcommand tree, that is not going to work.

**Comment by lespea** [comment]
Hmm interesting, I must have really messed something up.  Let me check when I get back to work on Monday and see what I did.  As far as I could tell I was adding switches to different sub-commands but I must have done something weird.

**Comment by lespea** [comment]
Sorry just got around to testing this.  The issue appears to be when validators are used:

```go
package main

import (
	"fmt"
	"github.com/akamensky/argparse"
	"os"
)

func validate(args []string) error {
	return nil
}

func main() {
	p := argparse.NewParser("test", "test")

	c1 := p.NewCommand("c1", "c1")
	c2 := p.NewCommand("c2", "c2")

	arg1 := c1.String("s", "str", &argparse.Options{
		Help:    "arg1 in c1",
		Validate: validate,
		Default: "arg1",
	})
	arg2 := c2.String("s", "str", &argparse.Options{
		Help:    "arg2 in c2",
		Validate: validate,
		Default: "arg2",
	})

	err := p.Parse(os.Args)
	if err != nil {
		panic(err)
	}

	if c1.Happened() {
		fmt.Println(*arg1)
	} else if c2.Happened() {
		fmt.Println(*arg2)
	} else {
		fmt.Println("pick either c1 or c2")
	}
}
```

Error:

```
go build -o test ./test.go && ./test
panic: unable to add String: short name o occurs more than once

goroutine 1 [running]:
github.com/akamensky/argparse.(*Command).String(0xc000120310, 0x10df47a, 0x1, 0x10df571, 0x3, 0xc000110300, 0xc000000124)
	/Users/z001j31/go/pkg/mod/github.com/akamensky/argparse@v1.2.2/argparse.go:251 +0x1f1
main.makeOpts(0xc000120000, 0xc0001200e0, 0xc00007c040)
	/Users/z001j31/devel/opttest/test.go:71 +0x157
main.main()
	/Users/z001j31/devel/opttest/test.go:173 +0xa5
```
